### ISSUE TITLE
UMD Module

### ISSUE THREAD

**Issue by positlabs** [essdot/spliddit#7]
It would be nice to have this tool work outside of commonjs, so we should wrap it up as some kind of UMD module.

https://github.com/umdjs/umd/blob/master/templates/commonjsStrict.js

**Comment by essdot** [comment]
Is there a tool that will do this, that can be added to the npm scripts or something? Would prefer not to rewrite the module

**Comment by positlabs** [comment]
No need to rewrite. I suggested a UMD wrapper because of its flexibility, but we could do something simpler than that. 

```
// self executing. sandboxes scope out of window
(function(){

  ...spliddit code...

  if(module){
    // common js exports
    module.exports = spliddit
    module.exports.isFirstOfPair = is_first_of_surrogate_pair
    module.exports.hasPair = has_pair
  }else{
    // assign to window
    spliddit.hasPair = has_pair;
    spliddit.isFirstOfPair = is_first_of_surrogate_pair;
    window.spliddit = spliddit;
  }
})();
```

This would prevent it from borking in a browser (because of lack of module.exports), and it would keep the global scope clean.

**Comment by essdot** [comment]
Still, I think the best thing is to keep such concerns out of the code itself. If the issue is borking in the browser, perhaps Browserify or Webpack could help?

**Comment by positlabs** [comment]
Oh, yeah that's a good idea. I've never done it before, but it seems simple enough. Here's a nice writeup.

http://makerlog.org/posts/creating-js-library-builds-with-browserify-and-other-npm-modules/

It would go something like this.
`browserify index.js --s spliddit > dist/spliddit.js`
