### ISSUE TITLE
Heart Emoji Issue

### ISSUE THREAD

**Issue by sallar** [essdot/spliddit#9]
Hi, 

your library is awesome. I didnt know about it and I made my own: https://github.com/sallar/stringz
There is one issue though, in your lib heart is recognized as two characters:

``` js
spliddit("❤️"); // ["❤", "️"];
```

Is there a way to fix this?
Thanks.

**Comment by ovr** [comment]
ping!

**Comment by sallar** [comment]
Ah apparently this is fixed in https://github.com/essdot/spliddit/pull/10 but hasn't been closes. I'll close this.
